// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Manual_screen_init(void)
{
ui_Manual = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Manual, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MSLabel1 = lv_label_create(ui_Manual);
lv_obj_set_width( ui_MSLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MSLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MSLabel1, -5 );
lv_obj_set_y( ui_MSLabel1, -109 );
lv_obj_set_align( ui_MSLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_MSLabel1,"Ручное управление");
lv_obj_set_style_text_font(ui_MSLabel1, &ui_font_Ubu, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Grid = lv_obj_create(ui_Manual);
lv_obj_remove_style_all(ui_Grid);
lv_obj_set_width( ui_Grid, lv_pct(100));
lv_obj_set_height( ui_Grid, lv_pct(90));
lv_obj_set_x( ui_Grid, lv_pct(0) );
lv_obj_set_y( ui_Grid, lv_pct(5) );
lv_obj_set_align( ui_Grid, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Grid,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Grid, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Grid, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Grid, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Grid, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Grid);
lv_obj_set_width( ui_Panel1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -2 );
lv_obj_set_y( ui_Label4, -9 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Шнек");
lv_obj_set_style_text_font(ui_Label4, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScrewSwitch = lv_switch_create(ui_Panel1);
lv_obj_set_width( ui_ScrewSwitch, 50);
lv_obj_set_height( ui_ScrewSwitch, 25);
lv_obj_set_align( ui_ScrewSwitch, LV_ALIGN_CENTER );


ui_Panel5 = lv_obj_create(ui_Grid);
lv_obj_set_width( ui_Panel5, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel5, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -2 );
lv_obj_set_y( ui_Label5, -9 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Насос");
lv_obj_set_style_text_font(ui_Label5, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PumpSwitch = lv_switch_create(ui_Panel5);
lv_obj_set_width( ui_PumpSwitch, 50);
lv_obj_set_height( ui_PumpSwitch, 25);
lv_obj_set_align( ui_PumpSwitch, LV_ALIGN_CENTER );


ui_Panel2 = lv_obj_create(ui_Grid);
lv_obj_set_width( ui_Panel2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -2 );
lv_obj_set_y( ui_Label1, -9 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Обдув");
lv_obj_set_style_text_font(ui_Label1, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FanSwitch = lv_switch_create(ui_Panel2);
lv_obj_set_width( ui_FanSwitch, 50);
lv_obj_set_height( ui_FanSwitch, 25);
lv_obj_set_align( ui_FanSwitch, LV_ALIGN_CENTER );


ui_Panel6 = lv_obj_create(ui_Grid);
lv_obj_set_width( ui_Panel6, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel6, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel6,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FanLabel = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_FanLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FanLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FanLabel, -2 );
lv_obj_set_y( ui_FanLabel, -9 );
lv_obj_set_align( ui_FanLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_FanLabel,"Обдув: 0%");
lv_obj_set_style_text_font(ui_FanLabel, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FanSlider = lv_slider_create(ui_Panel6);
lv_slider_set_value( ui_FanSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_FanSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_FanSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_FanSlider, 250);
lv_obj_set_height( ui_FanSlider, 10);
lv_obj_set_align( ui_FanSlider, LV_ALIGN_CENTER );


ui_Dropdown3 = lv_dropdown_create(ui_Manual);
lv_dropdown_set_options( ui_Dropdown3, "Главный\nРучное\nНастройки" );
lv_dropdown_set_selected_highlight( ui_Dropdown3, false);
lv_dropdown_set_text( ui_Dropdown3, " ");
lv_obj_set_width( ui_Dropdown3, 32);
lv_obj_set_height( ui_Dropdown3, 24);
lv_obj_add_flag( ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Dropdown3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dropdown3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown3, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown3), &ui_font_Ubu14,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(lv_dropdown_get_list(ui_Dropdown3), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(lv_dropdown_get_list(ui_Dropdown3), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_FanSlider, ui_event_FanSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Dropdown3, ui_event_Dropdown3, LV_EVENT_ALL, NULL);

}
