// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Main_screen_init(void)
{
ui_Main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MSLabel2 = lv_label_create(ui_Main);
lv_obj_set_width( ui_MSLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MSLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MSLabel2, -5 );
lv_obj_set_y( ui_MSLabel2, -109 );
lv_obj_set_align( ui_MSLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_MSLabel2,"Главный экран");
lv_obj_set_style_text_font(ui_MSLabel2, &ui_font_Ubu, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container7 = lv_obj_create(ui_Main);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_height( ui_Container7, 20);
lv_obj_set_width( ui_Container7, LV_SIZE_CONTENT);  /// 90
lv_obj_set_align( ui_Container7, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ChimneyImg = lv_img_create(ui_Container7);
lv_img_set_src(ui_ChimneyImg, &ui_img_1215070265);
lv_obj_set_width( ui_ChimneyImg, 24);
lv_obj_set_height( ui_ChimneyImg, lv_pct(100));
lv_obj_set_x( ui_ChimneyImg, -91 );
lv_obj_set_y( ui_ChimneyImg, -8 );
lv_obj_set_align( ui_ChimneyImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ChimneyImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ChimneyImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
// lv_obj_set_style_blend_mode(ui_ChimneyImg, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_opa(ui_ChimneyImg, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FireImg = lv_img_create(ui_Container7);
lv_img_set_src(ui_FireImg, &ui_img_1497467533);
lv_obj_set_width( ui_FireImg, 24);
lv_obj_set_height( ui_FireImg, lv_pct(100));
lv_obj_set_x( ui_FireImg, -91 );
lv_obj_set_y( ui_FireImg, -8 );
lv_obj_set_align( ui_FireImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FireImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FireImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container8 = lv_obj_create(ui_Main);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, lv_pct(100));
lv_obj_set_height( ui_Container8, lv_pct(100));
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempLabel = lv_label_create(ui_Container8);
lv_obj_set_width( ui_TempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempLabel, -42 );
lv_obj_set_y( ui_TempLabel, 1 );
lv_obj_set_align( ui_TempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempLabel,"20°");
lv_obj_set_style_text_font(ui_TempLabel, &ui_font_Ubu84, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempRoller = lv_roller_create(ui_Container8);
lv_roller_set_options( ui_TempRoller, "0°\n5°\n10°\n15°\n20°\n25°\n30°\n35°\n40°\n45°\n50°\n55°\n60°\n65°\n70°\n75°\n80°", LV_ROLLER_MODE_INFINITE );
lv_roller_set_selected( ui_TempRoller, 10, LV_ANIM_OFF);
lv_obj_set_height( ui_TempRoller, 200);
lv_obj_set_width( ui_TempRoller, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_TempRoller, -64 );
lv_obj_set_y( ui_TempRoller, 48 );
lv_obj_set_align( ui_TempRoller, LV_ALIGN_TOP_RIGHT );
lv_obj_set_style_text_color(ui_TempRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempRoller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TempRoller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempRoller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TempRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TempRoller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_TempRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempRoller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempRoller, &ui_font_Ubu28, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TempRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempRoller, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_TimeLabel = lv_label_create(ui_Main);
lv_obj_set_height( ui_TimeLabel, 20);
lv_obj_set_width( ui_TimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_TimeLabel, 3 );
lv_obj_set_y( ui_TimeLabel, 0 );
lv_obj_set_align( ui_TimeLabel, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_TimeLabel,"9:00 PM\n");
lv_obj_set_style_text_font(ui_TimeLabel, &ui_font_Ubu, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateLabel = lv_label_create(ui_Main);
lv_obj_set_height( ui_DateLabel, 20);
lv_obj_set_width( ui_DateLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_DateLabel, -3 );
lv_obj_set_y( ui_DateLabel, 0 );
lv_obj_set_align( ui_DateLabel, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_DateLabel,"20.07.2024");
lv_obj_set_style_text_font(ui_DateLabel, &ui_font_Ubu, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown2 = lv_dropdown_create(ui_Main);
lv_dropdown_set_options( ui_Dropdown2, "Главный\nРучное\nНастройки" );
lv_dropdown_set_selected_highlight( ui_Dropdown2, false);
lv_dropdown_set_text( ui_Dropdown2, " ");
lv_obj_set_width( ui_Dropdown2, 32);
lv_obj_set_height( ui_Dropdown2, 24);
lv_obj_add_flag( ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_align(ui_Dropdown2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown2, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(ui_Dropdown2, LV_TEXT_ALIGN_CENTER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown2), &ui_font_Ubu14,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(lv_dropdown_get_list(ui_Dropdown2), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(lv_dropdown_get_list(ui_Dropdown2), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);

}
