// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Settings_screen_init(void)
{
ui_Settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Settings, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MSLabel3 = lv_label_create(ui_Settings);
lv_obj_set_width( ui_MSLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MSLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MSLabel3, -5 );
lv_obj_set_y( ui_MSLabel3, -109 );
lv_obj_set_align( ui_MSLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_MSLabel3,"Настройки");
lv_obj_set_style_text_font(ui_MSLabel3, &ui_font_Ubu, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainTabView = lv_tabview_create(ui_Settings, LV_DIR_TOP, 30);
lv_obj_set_width( ui_MainTabView, 320);
lv_obj_set_height( ui_MainTabView, 206);
lv_obj_set_x( ui_MainTabView, 0 );
lv_obj_set_y( ui_MainTabView, 15 );
lv_obj_set_align( ui_MainTabView, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MainTabView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_MainTabView, LV_OBJ_FLAG_HIDDEN );   /// Flags


ui_Pump = lv_tabview_add_tab(ui_MainTabView, "Насос");
lv_obj_set_flex_flow(ui_Pump,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Pump, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_left(ui_Pump, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Pump, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Pump, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Pump, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Grid1 = lv_obj_create(ui_Pump);
lv_obj_remove_style_all(ui_Grid1);
lv_obj_set_width( ui_Grid1, lv_pct(100));
lv_obj_set_height( ui_Grid1, lv_pct(100));
lv_obj_set_x( ui_Grid1, lv_pct(0) );
lv_obj_set_y( ui_Grid1, lv_pct(5) );
lv_obj_set_align( ui_Grid1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Grid1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Grid1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Grid1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Grid1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Grid1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Grid1, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel11 = lv_obj_create(ui_Grid1);
lv_obj_set_width( ui_Panel11, lv_pct(100));
lv_obj_set_height( ui_Panel11, lv_pct(25));
lv_obj_set_align( ui_Panel11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel11,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel11, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_Panel11);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -2 );
lv_obj_set_y( ui_Label11, -9 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Темп. включения насоса");

ui_PumpOnTempInp = lv_textarea_create(ui_Panel11);
lv_obj_set_width( ui_PumpOnTempInp, 100);
lv_obj_set_height( ui_PumpOnTempInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_PumpOnTempInp, LV_ALIGN_LEFT_MID );
if (false) lv_textarea_set_accepted_chars(ui_PumpOnTempInp, NULL);
else lv_textarea_set_accepted_chars(ui_PumpOnTempInp, "1234567890");
lv_textarea_set_max_length(ui_PumpOnTempInp,5);
lv_textarea_set_placeholder_text(ui_PumpOnTempInp,"°");
lv_textarea_set_one_line(ui_PumpOnTempInp,true);
lv_obj_set_style_text_color(ui_PumpOnTempInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PumpOnTempInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PumpOnTempInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Panel10 = lv_obj_create(ui_Grid1);
lv_obj_set_width( ui_Panel10, lv_pct(100));
lv_obj_set_height( ui_Panel10, lv_pct(25));
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel10,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_Panel10);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -2 );
lv_obj_set_y( ui_Label10, -9 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Темп. выключения насоса");

ui_PumpOffTempInp = lv_textarea_create(ui_Panel10);
lv_obj_set_width( ui_PumpOffTempInp, 100);
lv_obj_set_height( ui_PumpOffTempInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_PumpOffTempInp, LV_ALIGN_LEFT_MID );
if (false) lv_textarea_set_accepted_chars(ui_PumpOffTempInp, NULL);
else lv_textarea_set_accepted_chars(ui_PumpOffTempInp, "1234567890");
lv_textarea_set_max_length(ui_PumpOffTempInp,5);
lv_textarea_set_placeholder_text(ui_PumpOffTempInp,"°");
lv_textarea_set_one_line(ui_PumpOffTempInp,true);
lv_obj_set_style_text_color(ui_PumpOffTempInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PumpOffTempInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PumpOffTempInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Motor = lv_tabview_add_tab(ui_MainTabView, "Шнек");
lv_obj_set_flex_flow(ui_Motor,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Motor, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_left(ui_Motor, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Motor, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Motor, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Motor, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Grid3 = lv_obj_create(ui_Motor);
lv_obj_remove_style_all(ui_Grid3);
lv_obj_set_width( ui_Grid3, lv_pct(100));
lv_obj_set_height( ui_Grid3, lv_pct(100));
lv_obj_set_x( ui_Grid3, lv_pct(0) );
lv_obj_set_y( ui_Grid3, lv_pct(5) );
lv_obj_set_align( ui_Grid3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Grid3,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Grid3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Grid3, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Grid3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Grid3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Grid3, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel12 = lv_obj_create(ui_Grid3);
lv_obj_set_width( ui_Panel12, lv_pct(100));
lv_obj_set_height( ui_Panel12, lv_pct(25));
lv_obj_set_align( ui_Panel12, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel12, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_Panel12);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -2 );
lv_obj_set_y( ui_Label12, -9 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Время работы шнека");

ui_ScrewInp = lv_textarea_create(ui_Panel12);
lv_obj_set_width( ui_ScrewInp, 100);
lv_obj_set_height( ui_ScrewInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_ScrewInp, LV_ALIGN_LEFT_MID );
if (false) lv_textarea_set_accepted_chars(ui_ScrewInp, NULL);
else lv_textarea_set_accepted_chars(ui_ScrewInp, "1234567890");
lv_textarea_set_max_length(ui_ScrewInp,5);
lv_textarea_set_placeholder_text(ui_ScrewInp,"sec");
lv_textarea_set_one_line(ui_ScrewInp,true);
lv_obj_set_style_text_color(ui_ScrewInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScrewInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScrewInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Panel15 = lv_obj_create(ui_Grid3);
lv_obj_set_width( ui_Panel15, lv_pct(100));
lv_obj_set_height( ui_Panel15, lv_pct(25));
lv_obj_set_align( ui_Panel15, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel15,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel15, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label15 = lv_label_create(ui_Panel15);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -2 );
lv_obj_set_y( ui_Label15, -9 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Интервал под. горючего");

ui_FuelDispIntervalInp = lv_textarea_create(ui_Panel15);
lv_obj_set_width( ui_FuelDispIntervalInp, 100);
lv_obj_set_height( ui_FuelDispIntervalInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_FuelDispIntervalInp, LV_ALIGN_LEFT_MID );
if (false) lv_textarea_set_accepted_chars(ui_FuelDispIntervalInp, NULL);
else lv_textarea_set_accepted_chars(ui_FuelDispIntervalInp, "1234567890");
lv_textarea_set_max_length(ui_FuelDispIntervalInp,5);
lv_textarea_set_placeholder_text(ui_FuelDispIntervalInp,"sec");
lv_textarea_set_one_line(ui_FuelDispIntervalInp,true);
lv_obj_set_style_text_color(ui_FuelDispIntervalInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FuelDispIntervalInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FuelDispIntervalInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Fan = lv_tabview_add_tab(ui_MainTabView, "Обдув");
lv_obj_set_flex_flow(ui_Fan,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Fan, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_left(ui_Fan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Fan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Fan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Fan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Grid4 = lv_obj_create(ui_Fan);
lv_obj_remove_style_all(ui_Grid4);
lv_obj_set_width( ui_Grid4, lv_pct(100));
lv_obj_set_height( ui_Grid4, lv_pct(100));
lv_obj_set_x( ui_Grid4, lv_pct(0) );
lv_obj_set_y( ui_Grid4, lv_pct(5) );
lv_obj_set_align( ui_Grid4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Grid4,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Grid4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Grid4, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Grid4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Grid4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Grid4, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel16 = lv_obj_create(ui_Grid4);
lv_obj_set_width( ui_Panel16, lv_pct(100));
lv_obj_set_height( ui_Panel16, lv_pct(25));
lv_obj_set_align( ui_Panel16, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel16,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel16, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label16 = lv_label_create(ui_Panel16);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, -2 );
lv_obj_set_y( ui_Label16, -9 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Темп. ухода в защиту");

ui_SafeModeTempInp = lv_textarea_create(ui_Panel16);
lv_obj_set_width( ui_SafeModeTempInp, 100);
lv_obj_set_height( ui_SafeModeTempInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_SafeModeTempInp, LV_ALIGN_LEFT_MID );
if (false) lv_textarea_set_accepted_chars(ui_SafeModeTempInp, NULL);
else lv_textarea_set_accepted_chars(ui_SafeModeTempInp, "1234567890");
lv_textarea_set_max_length(ui_SafeModeTempInp,5);
lv_textarea_set_placeholder_text(ui_SafeModeTempInp,"°");
lv_textarea_set_one_line(ui_SafeModeTempInp,true);
lv_obj_set_style_text_color(ui_SafeModeTempInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SafeModeTempInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SafeModeTempInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Panel17 = lv_obj_create(ui_Grid4);
lv_obj_set_width( ui_Panel17, lv_pct(100));
lv_obj_set_height( ui_Panel17, lv_pct(25));
lv_obj_set_align( ui_Panel17, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel17,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel17, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label17 = lv_label_create(ui_Panel17);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, -2 );
lv_obj_set_y( ui_Label17, -9 );
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Мощность в защите");

ui_SafeModePowerInp = lv_textarea_create(ui_Panel17);
lv_obj_set_width( ui_SafeModePowerInp, 100);
lv_obj_set_height( ui_SafeModePowerInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_SafeModePowerInp, LV_ALIGN_LEFT_MID );
if (false) lv_textarea_set_accepted_chars(ui_SafeModePowerInp, NULL);
else lv_textarea_set_accepted_chars(ui_SafeModePowerInp, "1234567890");
lv_textarea_set_max_length(ui_SafeModePowerInp,5);
lv_textarea_set_placeholder_text(ui_SafeModePowerInp,"%");
lv_textarea_set_one_line(ui_SafeModePowerInp,true);
lv_obj_set_style_text_color(ui_SafeModePowerInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SafeModePowerInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SafeModePowerInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Panel18 = lv_obj_create(ui_Grid4);
lv_obj_set_width( ui_Panel18, lv_pct(100));
lv_obj_set_height( ui_Panel18, lv_pct(25));
lv_obj_set_align( ui_Panel18, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel18,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel18, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Panel18, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_Panel18);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, -52 );
lv_obj_set_y( ui_Label18, -12 );
lv_obj_set_align( ui_Label18, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label18,"Шаг вентилятора");

ui_Container5 = lv_obj_create(ui_Panel18);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_height( ui_Container5, 50);
lv_obj_set_width( ui_Container5, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FanTickPercentInp = lv_textarea_create(ui_Container5);
lv_obj_set_width( ui_FanTickPercentInp, 52);
lv_obj_set_height( ui_FanTickPercentInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_FanTickPercentInp, 19 );
lv_obj_set_y( ui_FanTickPercentInp, 0 );
lv_obj_set_align( ui_FanTickPercentInp, LV_ALIGN_TOP_MID );
if (false) lv_textarea_set_accepted_chars(ui_FanTickPercentInp, NULL);
else lv_textarea_set_accepted_chars(ui_FanTickPercentInp, "1234567890");
lv_textarea_set_max_length(ui_FanTickPercentInp,3);
lv_textarea_set_placeholder_text(ui_FanTickPercentInp,"%");
lv_textarea_set_one_line(ui_FanTickPercentInp,true);
lv_obj_set_style_text_color(ui_FanTickPercentInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FanTickPercentInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FanTickPercentInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_FanTickIntervalInp = lv_textarea_create(ui_Container5);
lv_obj_set_width( ui_FanTickIntervalInp, 100);
lv_obj_set_height( ui_FanTickIntervalInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_FanTickIntervalInp, LV_ALIGN_LEFT_MID );
if (false) lv_textarea_set_accepted_chars(ui_FanTickIntervalInp, NULL);
else lv_textarea_set_accepted_chars(ui_FanTickIntervalInp, "1234567890");
lv_textarea_set_max_length(ui_FanTickIntervalInp,5);
lv_textarea_set_placeholder_text(ui_FanTickIntervalInp,"sec");
lv_textarea_set_one_line(ui_FanTickIntervalInp,true);
lv_obj_set_style_text_color(ui_FanTickIntervalInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FanTickIntervalInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FanTickIntervalInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Other = lv_tabview_add_tab(ui_MainTabView, "Другое");
lv_obj_set_flex_flow(ui_Other,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Other, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_left(ui_Other, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Other, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Other, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Other, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Grid5 = lv_obj_create(ui_Other);
lv_obj_remove_style_all(ui_Grid5);
lv_obj_set_width( ui_Grid5, lv_pct(100));
lv_obj_set_height( ui_Grid5, lv_pct(100));
lv_obj_set_x( ui_Grid5, lv_pct(0) );
lv_obj_set_y( ui_Grid5, lv_pct(5) );
lv_obj_set_align( ui_Grid5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Grid5,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Grid5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Grid5, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Grid5, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Grid5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Grid5, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel19 = lv_obj_create(ui_Grid5);
lv_obj_set_width( ui_Panel19, lv_pct(100));
lv_obj_set_height( ui_Panel19, lv_pct(25));
lv_obj_set_align( ui_Panel19, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel19,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel19, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel19, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label22 = lv_label_create(ui_Panel19);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label22, -2 );
lv_obj_set_y( ui_Label22, -9 );
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"Имя WiFi Сети");

ui_WiFiDropdown = lv_dropdown_create(ui_Panel19);
lv_dropdown_set_options( ui_WiFiDropdown, "-Выкл-\nСеть 1\nСеть 2\nСеть 3\nСеть 4\nСеть 5" );
lv_obj_set_width( ui_WiFiDropdown, 100);
lv_obj_set_height( ui_WiFiDropdown, 31);
lv_obj_set_align( ui_WiFiDropdown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WiFiDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_align(ui_WiFiDropdown, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WiFiDropdown, &ui_font_Ubu14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_WiFiDropdown, &lv_font_montserrat_14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_WiFiDropdown), &ui_font_Ubu14,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(lv_dropdown_get_list(ui_WiFiDropdown), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(lv_dropdown_get_list(ui_WiFiDropdown), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel20 = lv_obj_create(ui_Grid5);
lv_obj_set_width( ui_Panel20, lv_pct(100));
lv_obj_set_height( ui_Panel20, lv_pct(25));
lv_obj_set_align( ui_Panel20, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel20,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel20, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel20, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label23 = lv_label_create(ui_Panel20);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label23, -2 );
lv_obj_set_y( ui_Label23, -9 );
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"Пароль WiFi Сети");

ui_WiFiPass = lv_textarea_create(ui_Panel20);
lv_obj_set_width( ui_WiFiPass, 100);
lv_obj_set_height( ui_WiFiPass, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_WiFiPass, LV_ALIGN_LEFT_MID );
lv_textarea_set_max_length(ui_WiFiPass,32);
lv_obj_set_style_text_color(ui_WiFiPass, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WiFiPass, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WiFiPass, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Panel23 = lv_obj_create(ui_Grid5);
lv_obj_set_width( ui_Panel23, lv_pct(100));
lv_obj_set_height( ui_Panel23, lv_pct(25));
lv_obj_set_align( ui_Panel23, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel23,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel23, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel23, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label25 = lv_label_create(ui_Panel23);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label25, -2 );
lv_obj_set_y( ui_Label25, -9 );
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"Часовой пояс");

ui_TimezoneInp = lv_textarea_create(ui_Panel23);
lv_obj_set_width( ui_TimezoneInp, 100);
lv_obj_set_height( ui_TimezoneInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_TimezoneInp, LV_ALIGN_LEFT_MID );
if (false) lv_textarea_set_accepted_chars(ui_TimezoneInp, NULL);
else lv_textarea_set_accepted_chars(ui_TimezoneInp, "-+1234567890");
lv_textarea_set_max_length(ui_TimezoneInp,5);
lv_textarea_set_placeholder_text(ui_TimezoneInp,"00:00");
lv_textarea_set_one_line(ui_TimezoneInp,true);
lv_obj_set_style_text_color(ui_TimezoneInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimezoneInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimezoneInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Panel4 = lv_obj_create(ui_Grid5);
lv_obj_set_width( ui_Panel4, lv_pct(100));
lv_obj_set_height( ui_Panel4, lv_pct(25));
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -2 );
lv_obj_set_y( ui_Label3, -9 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Гистерезис котла");

ui_HysteresisInp = lv_textarea_create(ui_Panel4);
lv_obj_set_width( ui_HysteresisInp, 100);
lv_obj_set_height( ui_HysteresisInp, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( ui_HysteresisInp, LV_ALIGN_LEFT_MID );
if (false) lv_textarea_set_accepted_chars(ui_HysteresisInp, NULL);
else lv_textarea_set_accepted_chars(ui_HysteresisInp, "1234567890");
lv_textarea_set_max_length(ui_HysteresisInp,5);
lv_textarea_set_placeholder_text(ui_HysteresisInp,"°");
lv_textarea_set_one_line(ui_HysteresisInp,true);
lv_obj_set_style_text_color(ui_HysteresisInp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HysteresisInp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HysteresisInp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Keyboard1 = lv_keyboard_create(ui_Settings);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 140);
lv_obj_set_height( ui_Keyboard1, 120);
lv_obj_set_x( ui_Keyboard1, -87 );
lv_obj_set_y( ui_Keyboard1, 57 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_text_font(ui_Keyboard1, &lv_font_montserrat_14, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_Dropdown1 = lv_dropdown_create(ui_Settings);
lv_dropdown_set_options( ui_Dropdown1, "Главный\nРучное\nНастройки" );
lv_dropdown_set_selected_highlight( ui_Dropdown1, false);
lv_dropdown_set_text( ui_Dropdown1, " ");
lv_obj_set_width( ui_Dropdown1, 32);
lv_obj_set_height( ui_Dropdown1, 24);
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown1, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown1), &ui_font_Ubu14,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(lv_dropdown_get_list(ui_Dropdown1), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(lv_dropdown_get_list(ui_Dropdown1), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard2 = lv_keyboard_create(ui_Settings);
lv_obj_set_height( ui_Keyboard2, 88);
lv_obj_set_width( ui_Keyboard2, lv_pct(100));
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_text_font(ui_Keyboard2, &lv_font_montserrat_14, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_PassPanel = lv_obj_create(ui_Settings);
lv_obj_set_width( ui_PassPanel, lv_pct(70));
lv_obj_set_height( ui_PassPanel, lv_pct(75));
lv_obj_set_align( ui_PassPanel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_PassPanel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_PassPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
// lv_obj_add_flag( ui_PassPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PassPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Checkbox1 = lv_checkbox_create(ui_PassPanel);
lv_checkbox_set_text(ui_Checkbox1,"Инженерный режим");
lv_obj_set_width( ui_Checkbox1, lv_pct(90));
lv_obj_set_height( ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox1, -2 );
lv_obj_set_y( ui_Checkbox1, -67 );
lv_obj_set_align( ui_Checkbox1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Keyboard3 = lv_keyboard_create(ui_PassPanel);
lv_keyboard_set_mode(ui_Keyboard3,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_height( ui_Keyboard3, 120);
lv_obj_set_width( ui_Keyboard3, lv_pct(90));
lv_obj_set_x( ui_Keyboard3, -24 );
lv_obj_set_y( ui_Keyboard3, 16 );
lv_obj_set_align( ui_Keyboard3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard3, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_text_font(ui_Keyboard3, &lv_font_montserrat_14, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_PumpOnTempInp, ui_event_PumpOnTempInp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PumpOffTempInp, ui_event_PumpOffTempInp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScrewInp, ui_event_ScrewInp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FuelDispIntervalInp, ui_event_FuelDispIntervalInp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SafeModeTempInp, ui_event_SafeModeTempInp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SafeModePowerInp, ui_event_SafeModePowerInp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FanTickPercentInp, ui_event_FanTickPercentInp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FanTickIntervalInp, ui_event_FanTickIntervalInp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WiFiPass, ui_event_WiFiPass, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TimezoneInp, ui_event_TimezoneInp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HysteresisInp, ui_event_HysteresisInp, LV_EVENT_ALL, NULL);
// lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox1, ui_event_Checkbox1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard3, ui_event_Keyboard3, LV_EVENT_ALL, NULL);

}
