// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t *ui_Main;
lv_obj_t *ui_MSLabel2;
lv_obj_t *ui_Container7;
lv_obj_t *ui_ChimneyImg;
lv_obj_t *ui_FireImg;
lv_obj_t *ui_Container8;
lv_obj_t *ui_TempLabel;
lv_obj_t *ui_TempRoller;
lv_obj_t *ui_TimeLabel;
lv_obj_t *ui_DateLabel;
void ui_event_Dropdown2( lv_event_t * e);
lv_obj_t *ui_Dropdown2;


// SCREEN: ui_Manual
void ui_Manual_screen_init(void);
lv_obj_t *ui_Manual;
lv_obj_t *ui_MSLabel1;
lv_obj_t *ui_Grid;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label4;
lv_obj_t *ui_ScrewSwitch;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Label5;
lv_obj_t *ui_PumpSwitch;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_FanSwitch;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_FanLabel;
void ui_event_FanSlider( lv_event_t * e);
lv_obj_t *ui_FanSlider;
void ui_event_Dropdown3( lv_event_t * e);
lv_obj_t *ui_Dropdown3;


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
lv_obj_t *ui_Settings;
lv_obj_t *ui_MSLabel3;
lv_obj_t *ui_MainTabView;
lv_obj_t *ui_Pump;
lv_obj_t *ui_Grid1;
lv_obj_t *ui_Panel11;
lv_obj_t *ui_Label11;
void ui_event_PumpOnTempInp( lv_event_t * e);
lv_obj_t *ui_PumpOnTempInp;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Label10;
void ui_event_PumpOffTempInp( lv_event_t * e);
lv_obj_t *ui_PumpOffTempInp;
lv_obj_t *ui_Motor;
lv_obj_t *ui_Grid3;
lv_obj_t *ui_Panel12;
lv_obj_t *ui_Label12;
void ui_event_ScrewInp( lv_event_t * e);
lv_obj_t *ui_ScrewInp;
lv_obj_t *ui_Panel15;
lv_obj_t *ui_Label15;
void ui_event_FuelDispIntervalInp( lv_event_t * e);
lv_obj_t *ui_FuelDispIntervalInp;
lv_obj_t *ui_Fan;
lv_obj_t *ui_Grid4;
lv_obj_t *ui_Panel16;
lv_obj_t *ui_Label16;
void ui_event_SafeModeTempInp( lv_event_t * e);
lv_obj_t *ui_SafeModeTempInp;
lv_obj_t *ui_Panel17;
lv_obj_t *ui_Label17;
void ui_event_SafeModePowerInp( lv_event_t * e);
lv_obj_t *ui_SafeModePowerInp;
lv_obj_t *ui_Panel18;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Container5;
void ui_event_FanTickPercentInp( lv_event_t * e);
lv_obj_t *ui_FanTickPercentInp;
void ui_event_FanTickIntervalInp( lv_event_t * e);
lv_obj_t *ui_FanTickIntervalInp;
lv_obj_t *ui_Other;
lv_obj_t *ui_Grid5;
lv_obj_t *ui_Panel19;
lv_obj_t *ui_Label22;
lv_obj_t *ui_WiFiDropdown;
lv_obj_t *ui_Panel20;
lv_obj_t *ui_Label23;
void ui_event_WiFiPass( lv_event_t * e);
lv_obj_t *ui_WiFiPass;
lv_obj_t *ui_Panel23;
lv_obj_t *ui_Label25;
void ui_event_TimezoneInp( lv_event_t * e);
lv_obj_t *ui_TimezoneInp;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Label3;
void ui_event_HysteresisInp( lv_event_t * e);
lv_obj_t *ui_HysteresisInp;
void ui_event_Keyboard1( lv_event_t * e);
lv_obj_t *ui_Keyboard1;
void ui_event_Dropdown1( lv_event_t * e);
lv_obj_t *ui_Dropdown1;
void ui_event_Keyboard2( lv_event_t * e);
lv_obj_t *ui_Keyboard2;
lv_obj_t *ui_PassPanel;
void ui_event_Checkbox1( lv_event_t * e);
lv_obj_t *ui_Checkbox1;
void ui_event_Keyboard3( lv_event_t * e);
lv_obj_t *ui_Keyboard3;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1826588228[1] = {&ui_img_1497467533};
const lv_img_dsc_t *ui_imgset_1183274112[1] = {&ui_img_1215070265};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Dropdown2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
}
}
void ui_event_FanSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_FanLabel, target, "Обдув: ", "%");
}
}
void ui_event_Dropdown3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
}
}
void ui_event_PumpOnTempInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_PumpOnTempInp);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_PumpOffTempInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_PumpOffTempInp);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_ScrewInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_ScrewInp);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_FuelDispIntervalInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_FuelDispIntervalInp);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_SafeModeTempInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_SafeModeTempInp);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_SafeModePowerInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_SafeModePowerInp);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_FanTickPercentInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_Keyboard1,  ui_FanTickPercentInp);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_FanTickIntervalInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_FanTickIntervalInp);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_WiFiPass( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_Keyboard2,  ui_WiFiPass);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TimezoneInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_TimezoneInp);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_HysteresisInp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_HysteresisInp);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_Dropdown1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
}
}
void ui_event_Keyboard2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_Checkbox1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_Keyboard3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_PassPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_MainTabView, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Main_screen_init();
ui_Manual_screen_init();
ui_Settings_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Main);
}
