// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"
    
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_MSLabel2;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_ChimneyImg;
extern lv_obj_t *ui_FireImg;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_TempLabel;
extern lv_obj_t *ui_TempRoller;
extern lv_obj_t *ui_TimeLabel;
extern lv_obj_t *ui_DateLabel;
void ui_event_Dropdown2( lv_event_t * e);
extern lv_obj_t *ui_Dropdown2;
// SCREEN: ui_Manual
void ui_Manual_screen_init(void);
extern lv_obj_t *ui_Manual;
extern lv_obj_t *ui_MSLabel1;
extern lv_obj_t *ui_Grid;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_ScrewSwitch;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_PumpSwitch;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_FanSwitch;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_FanLabel;
void ui_event_FanSlider( lv_event_t * e);
extern lv_obj_t *ui_FanSlider;
void ui_event_Dropdown3( lv_event_t * e);
extern lv_obj_t *ui_Dropdown3;
// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_MSLabel3;
extern lv_obj_t *ui_MainTabView;
extern lv_obj_t *ui_Pump;
extern lv_obj_t *ui_Grid1;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Label11;
void ui_event_PumpOnTempInp( lv_event_t * e);
extern lv_obj_t *ui_PumpOnTempInp;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Label10;
void ui_event_PumpOffTempInp( lv_event_t * e);
extern lv_obj_t *ui_PumpOffTempInp;
extern lv_obj_t *ui_Motor;
extern lv_obj_t *ui_Grid3;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Label12;
void ui_event_ScrewInp( lv_event_t * e);
extern lv_obj_t *ui_ScrewInp;
extern lv_obj_t *ui_Panel15;
extern lv_obj_t *ui_Label15;
void ui_event_FuelDispIntervalInp( lv_event_t * e);
extern lv_obj_t *ui_FuelDispIntervalInp;
extern lv_obj_t *ui_Fan;
extern lv_obj_t *ui_Grid4;
extern lv_obj_t *ui_Panel16;
extern lv_obj_t *ui_Label16;
void ui_event_SafeModeTempInp( lv_event_t * e);
extern lv_obj_t *ui_SafeModeTempInp;
extern lv_obj_t *ui_Panel17;
extern lv_obj_t *ui_Label17;
void ui_event_SafeModePowerInp( lv_event_t * e);
extern lv_obj_t *ui_SafeModePowerInp;
extern lv_obj_t *ui_Panel18;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Container5;
void ui_event_FanTickPercentInp( lv_event_t * e);
extern lv_obj_t *ui_FanTickPercentInp;
void ui_event_FanTickIntervalInp( lv_event_t * e);
extern lv_obj_t *ui_FanTickIntervalInp;
extern lv_obj_t *ui_Other;
extern lv_obj_t *ui_Grid5;
extern lv_obj_t *ui_Panel19;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_WiFiDropdown;
extern lv_obj_t *ui_Panel20;
extern lv_obj_t *ui_Label23;
void ui_event_WiFiPass( lv_event_t * e);
extern lv_obj_t *ui_WiFiPass;
extern lv_obj_t *ui_Panel23;
extern lv_obj_t *ui_Label25;
void ui_event_TimezoneInp( lv_event_t * e);
extern lv_obj_t *ui_TimezoneInp;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label3;
void ui_event_HysteresisInp( lv_event_t * e);
extern lv_obj_t *ui_HysteresisInp;
void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
void ui_event_Dropdown1( lv_event_t * e);
extern lv_obj_t *ui_Dropdown1;
void ui_event_Keyboard2( lv_event_t * e);
extern lv_obj_t *ui_Keyboard2;
extern lv_obj_t *ui_PassPanel;
void ui_event_Checkbox1( lv_event_t * e);
extern lv_obj_t *ui_Checkbox1;
void ui_event_Keyboard3( lv_event_t * e);
extern lv_obj_t *ui_Keyboard3;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1215070265);   // assets/chimney-2.png
LV_IMG_DECLARE( ui_img_1497467533);   // assets/bonfire-2.png


LV_FONT_DECLARE( ui_font_Ubu);
LV_FONT_DECLARE( ui_font_Ubu14);
LV_FONT_DECLARE( ui_font_Ubu28);
LV_FONT_DECLARE( ui_font_Ubu84);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
