// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


void ui_event_comp_Dropdown1_Dropdown1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_Dropdown1 = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_screen_change( &ui_Manual, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Manual_screen_init);
}
}

// COMPONENT Dropdown1

lv_obj_t *ui_Dropdown1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Dropdown1;
cui_Dropdown1 = lv_dropdown_create(comp_parent);
lv_dropdown_set_options( cui_Dropdown1, "Main\nManual" );
lv_dropdown_set_selected_highlight( cui_Dropdown1, false);
lv_dropdown_set_text( cui_Dropdown1, " ");
lv_obj_set_width( cui_Dropdown1, 32);
lv_obj_set_height( cui_Dropdown1, 24);
lv_obj_add_flag( cui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

lv_obj_set_style_text_color(cui_Dropdown1, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Dropdown1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DROPDOWN1_NUM);
children[UI_COMP_DROPDOWN1_DROPDOWN1] = cui_Dropdown1;
lv_obj_add_event_cb(cui_Dropdown1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Dropdown1, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_Dropdown1, ui_event_comp_Dropdown1_Dropdown1, LV_EVENT_ALL, children);
ui_comp_Dropdown1_create_hook(cui_Dropdown1);
return cui_Dropdown1; 
}

